In [58]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [64]:
column_types = {
    "Cabin":str,
    "Embarked":str
}

In [65]:
titanic = pd.read_csv("D:\\Projets\\python\\titanic\\titanic.csv",dtype=column_types)

In [66]:
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [67]:
#exploratory data analysis

In [92]:
titanic["Cabin"]=titanic["Cabin"].astype(str)
titanic["Embarked"]=titanic["Embarked"].astype(str)

In [93]:
titanic.shape

(891, 12)

In [94]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [95]:
np.unique(titanic["Survived"])

array([0, 1], dtype=int64)

In [96]:
np.unique(titanic["Pclass"])

array([1, 2, 3], dtype=int64)

In [97]:
len(np.unique(titanic["Name"]))

891

In [98]:
np.unique(titanic["Sex"])

array(['female', 'male'], dtype=object)

In [99]:
np.unique(titanic["Age"])

array([ 0.42,  0.67,  0.75,  0.83,  0.92,  1.  ,  2.  ,  3.  ,  4.  ,
        5.  ,  6.  ,  7.  ,  8.  ,  9.  , 10.  , 11.  , 12.  , 13.  ,
       14.  , 14.5 , 15.  , 16.  , 17.  , 18.  , 19.  , 20.  , 20.5 ,
       21.  , 22.  , 23.  , 23.5 , 24.  , 24.5 , 25.  , 26.  , 27.  ,
       28.  , 28.5 , 29.  , 30.  , 30.5 , 31.  , 32.  , 32.5 , 33.  ,
       34.  , 34.5 , 35.  , 36.  , 36.5 , 37.  , 38.  , 39.  , 40.  ,
       40.5 , 41.  , 42.  , 43.  , 44.  , 45.  , 45.5 , 46.  , 47.  ,
       48.  , 49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 55.5 ,
       56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
       65.  , 66.  , 70.  , 70.5 , 71.  , 74.  , 80.  ,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,

In [100]:
len(titanic[titanic["Age"].isnull()])

177

In [117]:
titanic["Age"].isnull().sum()

177

In [101]:
np.unique(titanic["SibSp"])

array([0, 1, 2, 3, 4, 5, 8], dtype=int64)

In [102]:
np.unique(titanic["Parch"])

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [135]:
#np.unique(titanic["Ticket"])

In [136]:
len(np.unique(titanic["Ticket"]))

681

In [104]:
len(np.unique(titanic["Fare"]))

248

In [115]:
np.unique(titanic["Cabin"])

array(['A10', 'A14', 'A16', 'A19', 'A20', 'A23', 'A24', 'A26', 'A31',
       'A32', 'A34', 'A36', 'A5', 'A6', 'A7', 'B101', 'B102', 'B18',
       'B19', 'B20', 'B22', 'B28', 'B3', 'B30', 'B35', 'B37', 'B38',
       'B39', 'B4', 'B41', 'B42', 'B49', 'B5', 'B50', 'B51 B53 B55',
       'B57 B59 B63 B66', 'B58 B60', 'B69', 'B71', 'B73', 'B77', 'B78',
       'B79', 'B80', 'B82 B84', 'B86', 'B94', 'B96 B98', 'C101', 'C103',
       'C104', 'C106', 'C110', 'C111', 'C118', 'C123', 'C124', 'C125',
       'C126', 'C128', 'C148', 'C2', 'C22 C26', 'C23 C25 C27', 'C30',
       'C32', 'C45', 'C46', 'C47', 'C49', 'C50', 'C52', 'C54', 'C62 C64',
       'C65', 'C68', 'C7', 'C70', 'C78', 'C82', 'C83', 'C85', 'C86',
       'C87', 'C90', 'C91', 'C92', 'C93', 'C95', 'C99', 'D', 'D10 D12',
       'D11', 'D15', 'D17', 'D19', 'D20', 'D21', 'D26', 'D28', 'D30',
       'D33', 'D35', 'D36', 'D37', 'D45', 'D46', 'D47', 'D48', 'D49',
       'D50', 'D56', 'D6', 'D7', 'D9', 'E10', 'E101', 'E12', 'E121',
       'E17',

In [131]:
len(titanic[titanic["Cabin"]=='nan'])

687

In [107]:
np.unique(titanic["Embarked"])

array(['C', 'Q', 'S', 'nan'], dtype=object)

In [130]:
len(titanic[titanic["Embarked"]=='nan'])

2

In [138]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [137]:

#Survived
#Pclass
#Sex 
#Age only 177 nan
#SibSp
#Parch
# Fare
# Embarked only 2 nan

In [159]:
titanic_reduced = titanic.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1)

In [160]:
titanic_reduced.head(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [161]:
#encoding

In [162]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [163]:
encoder = LabelEncoder()

In [164]:
titanic_reduced["Sex"]=encoder.fit_transform(titanic_reduced["Sex"])
titanic_reduced["Embarked"] = encoder.fit_transform(titanic_reduced["Embarked"])

In [165]:
titanic_reduced.head(5)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [166]:
#### normalisation

In [167]:
standardiser = StandardScaler()

In [170]:
titan = standardiser.fit_transform(titanic_reduced)

In [169]:
titanic_reduced

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0   NaN      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [ ]:
#remove nan 

In [192]:
titanic_reduced.dropna(axis = 0 , inplace=True)

In [195]:
titanic_reduced.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [197]:
X = titanic_reduced[["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]
y = titanic_reduced["Survived"]

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [200]:
#model 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [201]:
model = KNeighborsClassifier()

In [202]:
param_grid = {
    "n_neighbors":np.arange(1,50),
    "metric" : ['minkowski','euclidean','manhattan']
}

In [203]:
grid = GridSearchCV(model,param_grid=param_grid,cv = 5)


In [204]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])})

In [205]:
grid.best_score_

0.7321128909229595

In [206]:
grid.best_params_

{'metric': 'manhattan', 'n_neighbors': 21}